class Strings {
  static final String welcomeToRadioActive = 'Welcome To \nRadioActive';
  static final String listenLive = 'Listen\nLive';
  static final String musicMatters = 'music\nmatters';
  static final String liveOnRadioActive = 'Live\nOn RadioActive';
  static final String lastTracksAired = 'Last tracks aired';
  static final String more = 'More';
  static final String showSchedule = 'Show Schedule';
  static final String now = 'Now';
  static final String next = 'Next';
  static String nowSchedule = 'Good Morning Sunshine';
  static final String nextSchedule = 'RadioActive Gold';
  static String songName = '';
  static String artist = '';
  static String imageUrl = '';
  static String time = '';
  static final String genre = 'Samprayadaya';
  static String song1 = 'Song1';
  static String song2 = 'Song2';
  static String song3 = 'Song3';
  static String song4 = 'Song4';
  static String song5 = 'Song5';
  static String artist1 = 'Artist1';
  static String artist2 = 'Artist2';
  static String artist3 = 'Artist3';
  static String artist4 = 'Artist4';
  static String artist5 = 'Artist5';
  static final String nowPlaying = 'Now Playing';
  static final String donateToRadioActive = 'Donate To\nRadioActive';
  static final String last5TracksAired = 'Last five Tracks Aired';
  static final String about = 'About Us';
  static final String aboutDetails = 'Sifnos island, July 16th 1999, first time “On The Air”…\nEver since Active, 24 hours, 365 days!\nOur music can be heard all over the rest of the Cycladic Islands (Mykonos, Syros, Serifos, Tinos, Paros, Naxos, Ios, Amorgos, Sikinos, Folegandros), to name a few. \nThe music is eclectic and very particular. Music is an international language, brings people from all over the world together and has no boundaries!\nThe changes between music styles are very interesting (to say the least). RadioActive won’t bore you!\nRadioActive’s studio is located in Artemon (the most beautiful village of Sifnos) and it utilizes the latest in digital technology with unsurpassed audio quality!\nThe signal is transferred digitally from the studio to the highest mountain top in the island and from there is transmitted to the whole Aegean Sea.\n\nLink, Listen Live and interact socially with us because …Music Matters';
  static final String donateDetails = 'RadioActive is a NON commercial Radio, a labor of love and love of music.\nRadioActive is a global family of music lovers. We strive to broadcast diverse and unique music that excites, inspires and moves you. RadioActive is where eclecticism is celebrated and niche music takes center stage. It’s where passionate people, not algorithms, play exceptional music that is hard to find anywhere else.\nAll without on-air advertising.\n\nHowever, we need a more sustainable model to keep doing what we’re doing, and cover the high costs of music licensing, our streaming infrastructure and radio production.\nWe believe the best way to achieve this is through listener support – we’d rather do this with you than anyone else.\n\nWe’re asking listeners to support RadioActive simply because YOUR SUPPORT MATTERS…';
  static final String donate = 'Donate';
  static final String supportRadioActive = 'Support RadioActive';
  static final String currentShow = 'Current Show';
  static final String weeklySchedule = 'Weekly Schedule';

  static final String radioUrl192 = 'https://streamyourdream.org:8074/stream';
  static final String radioUrl64 = 'https://streamyourdream.org:8020/stream';

  static const String contactMail = 'mailto:<info@radioactivefm.gr>?subject=<subject>&body=<Hello>';
  static final String contactPhone = '+302284032320';
  static final String instagramUrl = 'https://www.instagram.com/radioactive913';
  static final String facebookUrl = 'https://www.facebook.com/Radioactive.Sifnos';
  static final String twitterUrl = 'https://twitter.com/radioactive913';
  static final String spotifyUrl = 'https://open.spotify.com/user/radioactive913';
  static final String mixCloudUrl = 'https://www.mixcloud.com/radioactive913';
  static final String soundCloudUrl = 'https://soundcloud.com/radioactive913';
  static final String tumblrUrl = 'https://radioactive913.tumblr.com/';
  static final String donateUrl = 'https://radioactivefm.gr/about-us/?payment-mode=paypal';
  static final String termsNConditionsUrl = 'https://radioactivefm.gr/terms-of-use-mobile-app';
  static final String privacyUrl = 'https://radioactivefm.gr/privacy-policy-mobile-app';
}